// FlyToday.ir API adapter
// FlyToday requires xToken (generated by CAPTCHA) — may fail gracefully

const FLYTODAY_SEARCH_URL = "https://www.flytoday.ir/api/gateway/V1/flight/search";

function generateFlyTodayHeaders(params) {
  const searchPath = `https://www.flytoday.ir/flight/search?departure=${params.origin.toLowerCase()},1&arrival=${params.destination.toLowerCase()},2&departureDate=${params.departureDate}&adt=${params.adult}&chd=${params.child}&inf=${params.infant}&cabin=1&isDomestic=true&isAnyWhere=false`;

  return {
    "accept": "application/json, text/plain, */*",
    "accept-language": "fa",
    "content-type": "application/json",
    "origin": "https://www.flytoday.ir",
    "referer": searchPath,
    "x-app": "www.flytoday.ir",
    "x-currency": "IRR",
    "x-origin": "https://www.flytoday.ir",
    "x-path": searchPath,
    "x-proxy-cache": "no-store",
    "sec-ch-ua": '"Not;A=Brand";v="8", "Chromium";v="136", "Google Chrome";v="136"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": '"Windows"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36"
  };
}

/**
 * Search flights on FlyToday.ir
 * Returns empty array if CAPTCHA/rate-limited (does NOT throw)
 */
async function searchFlyToday(params) {
  const headers = generateFlyTodayHeaders(params);

  const originDestinationInformations = [
    {
      departureDateTime: params.departureDate,
      destinationLocationCode: params.destination,
      destinationType: "Airport",
      originLocationCode: params.origin,
      originType: "City"
    }
  ];

  if (params.returnDate) {
    originDestinationInformations.push({
      departureDateTime: params.returnDate,
      destinationLocationCode: params.origin,
      destinationType: "Airport",
      originLocationCode: params.destination,
      originType: "City"
    });
  }

  const body = {
    pricingSourceType: 0,
    adultCount: params.adult,
    childCount: params.child,
    infantCount: params.infant,
    travelPreference: {
      cabinType: "Y",
      maxStopsQuantity: "All",
      airTripType: params.returnDate ? "RoundTrip" : "OneWay"
    },
    originDestinationInformations,
    isJalali: true
  };

  try {
    const res = await fetch(FLYTODAY_SEARCH_URL, {
      method: "POST",
      headers,
      body: JSON.stringify(body),
      credentials: "include"
    });

    // 429 or captcha required — return empty, don't throw
    if (res.status === 429) {
      console.warn("[flytoday] Rate limited (429) — skipping");
      return [];
    }

    const data = await res.json();

    // Check for captcha header in response
    if (data["x-captcha-required"] === true) {
      console.warn("[flytoday] CAPTCHA required — skipping");
      return [];
    }

    if (!data.pricedItineraries || !Array.isArray(data.pricedItineraries)) {
      return [];
    }

    return data.pricedItineraries.map(itin => normalizeFlyTodayFlight(itin, params));
  } catch (err) {
    console.warn("[flytoday] Network error:", err.message);
    return [];
  }
}

function normalizeFlyTodayFlight(itin, params) {
  const segment = itin.originDestinationOptions?.[0]?.flightSegments?.[0];
  const pricing = itin.airItineraryPricingInfo?.itinTotalFare;
  const opAirline = segment?.operatingAirline;

  const dep = segment?.departureDateTime || "";
  const arr = segment?.arrivalDateTime || "";
  const duration = parseDuration(dep, arr);

  return {
    id: `flytoday_${itin.key || itin.fareSourceCode}`,
    source: "flytoday",
    airline: {
      code: itin.validatingAirlineCode,
      nameFa: getAirlineNameFa(itin.validatingAirlineCode),
      nameEn: itin.validatingAirlineCode,
      logo: getAirlineLogo(itin.validatingAirlineCode)
    },
    flightNumber: segment?.flightNumber || "",
    departure: dep,
    arrival: arr,
    duration,
    origin: params.origin,
    destination: params.destination,
    prices: {
      adult: pricing?.totalFare || 0,
      child: pricing?.totalFare || 0,
      infant: 0
    },
    seatsRemaining: segment?.seatsRemaining ?? null,
    aircraft: opAirline?.equipmentName || opAirline?.equipment || "",
    isCharter: itin.isCharter || false,
    isRefundable: itin.refundMethod === "Online",
    cabinClass: segment?.cabinClassName || "اکونومی",
    baggage: segment?.baggageLocal || segment?.baggage || null,
    cancellationRules: null,
    bookingUrl: `https://www.flytoday.ir/flight/search?departure=${params.origin.toLowerCase()},1&arrival=${params.destination.toLowerCase()},2&departureDate=${params.departureDate}&adt=${params.adult}&chd=${params.child}&inf=${params.infant}&cabin=1&isDomestic=true`
  };
}

function getAirlineNameFa(code) {
  const map = {
    NV: "کارون", ZV: "زاگرس", ISP: "جی‌اسکای", I3: "آتا", EP: "آسمان",
    TKN: "فلای‌کیش", W5: "ماهان", IR: "ایران‌ایر", SE: "ساها",
    HH: "قشم‌ایر", Y9: "کاسپین", PA: "پارس‌ایر"
  };
  return map[code] || code;
}

function getAirlineLogo(code) {
  const map = {
    TKN: "https://cdn.alibaba.ir/static/img/airlines/Domestic/FK.png",
    ISP: "https://cdn.alibaba.ir/static/img/airlines/Domestic/JS.png",
    NV: "https://cdn.alibaba.ir/static/img/airlines/Domestic/NV.png",
    ZV: "https://cdn.alibaba.ir/static/img/airlines/Domestic/ZV.png",
    I3: "https://cdn.alibaba.ir/static/img/airlines/Domestic/I3.png",
    EP: "https://cdn.alibaba.ir/static/img/airlines/Domestic/EP.png"
  };
  return map[code] || "";
}

if (typeof module !== 'undefined') {
  module.exports = { searchFlyToday, normalizeFlyTodayFlight };
}
